"""add_fine_tier_is_mandatory_check_type_to_rules

Revision ID: 0cdd1cbf1525
Revises: 9c6a4fe3c1ce
Create Date: 2026-05-30 01:30:07.695093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdd1cbf1525'
down_revision: Union[str, Sequence[str], None] = '9c6a4fe3c1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('regulation_versions_regulation_idx'), table_name='regulation_versions')
    op.create_index(op.f('ix_regulation_versions_regulation_id'), 'regulation_versions', ['regulation_id'], unique=False)
    op.add_column('rule_versions', sa.Column('fine_tier', sa.String(length=10), nullable=True))
    op.add_column('rule_versions', sa.Column('is_mandatory', sa.Boolean(), nullable=True))
    op.drop_index(op.f('rule_versions_regulation_version_idx'), table_name='rule_versions')
    op.drop_index(op.f('rule_versions_rule_idx'), table_name='rule_versions')
    op.create_index(op.f('ix_rule_versions_regulation_version_id'), 'rule_versions', ['regulation_version_id'], unique=False)
    op.create_index(op.f('ix_rule_versions_rule_id'), 'rule_versions', ['rule_id'], unique=False)
    op.add_column('rules', sa.Column('fine_tier', sa.String(length=10), nullable=True))
    op.add_column('rules', sa.Column('is_mandatory', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('rules', sa.Column('check_type', sa.String(length=30), nullable=False, server_default=sa.text("'informational'")))
    op.drop_index(op.f('rules_category_idx'), table_name='rules')
    op.drop_index(op.f('rules_embedding_idx'), table_name='rules', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('rules_is_active_idx'), table_name='rules')
    op.drop_index(op.f('rules_regulation_idx'), table_name='rules')
    op.drop_index(op.f('rules_regulation_version_idx'), table_name='rules')
    op.drop_index(op.f('rules_severity_idx'), table_name='rules')
    op.drop_index(op.f('rules_tags_idx'), table_name='rules', postgresql_using='gin')
    op.create_index(op.f('ix_rules_category'), 'rules', ['category'], unique=False)
    op.create_index(op.f('ix_rules_check_type'), 'rules', ['check_type'], unique=False)
    op.create_index(op.f('ix_rules_fine_tier'), 'rules', ['fine_tier'], unique=False)
    op.create_index(op.f('ix_rules_regulation_id'), 'rules', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_rules_regulation_version_id'), 'rules', ['regulation_version_id'], unique=False)
    op.create_index('ix_rules_is_active', 'rules', ['is_active'], unique=False)
    op.create_index('ix_rules_severity', 'rules', ['severity'], unique=False)
    op.create_index('ix_rules_applicability_tags', 'rules', ['applicability_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_rules_embedding', 'rules', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rules_embedding', table_name='rules', postgresql_using='ivfflat')
    op.drop_index('ix_rules_applicability_tags', table_name='rules', postgresql_using='gin')
    op.drop_index('ix_rules_severity', table_name='rules')
    op.drop_index('ix_rules_is_active', table_name='rules')
    op.drop_index(op.f('ix_rules_regulation_version_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_regulation_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_fine_tier'), table_name='rules')
    op.drop_index(op.f('ix_rules_check_type'), table_name='rules')
    op.drop_index(op.f('ix_rules_category'), table_name='rules')
    op.create_index(op.f('rules_tags_idx'), 'rules', ['applicability_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('rules_severity_idx'), 'rules', ['severity'], unique=False)
    op.create_index(op.f('rules_regulation_version_idx'), 'rules', ['regulation_version_id'], unique=False)
    op.create_index(op.f('rules_regulation_idx'), 'rules', ['regulation_id'], unique=False)
    op.create_index(op.f('rules_is_active_idx'), 'rules', ['is_active'], unique=False)
    op.create_index(op.f('rules_embedding_idx'), 'rules', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('rules_category_idx'), 'rules', ['category'], unique=False)
    op.drop_column('rules', 'check_type')
    op.drop_column('rules', 'is_mandatory')
    op.drop_column('rules', 'fine_tier')
    op.drop_index(op.f('ix_rule_versions_rule_id'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_regulation_version_id'), table_name='rule_versions')
    op.create_index(op.f('rule_versions_rule_idx'), 'rule_versions', ['rule_id'], unique=False)
    op.create_index(op.f('rule_versions_regulation_version_idx'), 'rule_versions', ['regulation_version_id'], unique=False)
    op.drop_column('rule_versions', 'is_mandatory')
    op.drop_column('rule_versions', 'fine_tier')
    op.drop_index(op.f('ix_regulation_versions_regulation_id'), table_name='regulation_versions')
    op.create_index(op.f('regulation_versions_regulation_idx'), 'regulation_versions', ['regulation_id'], unique=False)
    # ### end Alembic commands ###``