"""add_processors_table

Revision ID: 385081b467cb
Revises: 742f918d9aaf
Create Date: 2026-06-20 14:59:04.795283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '385081b467cb'
down_revision: Union[str, Sequence[str], None] = '742f918d9aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('data_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('data_subject_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('processing_locations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('transfer_mechanism', sa.Enum('scc', 'bcr', 'adequacy_decision', 'derogation', 'none', name='processortransfermechanism'), nullable=True),
    sa.Column('dpa_signed', sa.Boolean(), nullable=False),
    sa.Column('dpa_date', sa.Date(), nullable=True),
    sa.Column('contract_review_date', sa.Date(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='processorrisk'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'under_review', name='processorstatus'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'auto_generated', name='processorsource'), nullable=False),
    sa.Column('sub_processors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_processors_category'), 'processors', ['category'], unique=False)
    op.create_index(op.f('ix_processors_status'), 'processors', ['status'], unique=False)
    op.create_index(op.f('ix_processors_tenant_id'), 'processors', ['tenant_id'], unique=False)
    op.execute("ALTER TABLE processors ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE processors FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON processors
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processors_tenant_id'), table_name='processors')
    op.drop_index(op.f('ix_processors_status'), table_name='processors')
    op.drop_index(op.f('ix_processors_category'), table_name='processors')
    op.drop_table('processors')
    # ### end Alembic commands ###
