"""add_ropa_entries_table

Revision ID: 44f5e10e6092
Revises: cbbf5b013bae
Create Date: 2026-06-06 21:12:46.591668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44f5e10e6092'
down_revision: Union[str, Sequence[str], None] = 'cbbf5b013bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ropa_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('regulation_id', sa.Uuid(), nullable=False),
    sa.Column('source_profile_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('data_role', sa.Enum('controller', 'processor', name='ropadatarole'), nullable=False),
    sa.Column('activity_name', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.Enum('consent', 'contract', 'legal_obligation', 'vital_interests', 'public_task', 'legitimate_interests', name='ropalegalbasis'), nullable=False),
    sa.Column('legal_obligation_reference', sa.Text(), nullable=True),
    sa.Column('legitimate_interest_description', sa.Text(), nullable=True),
    sa.Column('data_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('data_subject_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('has_special_category_data', sa.Boolean(), nullable=False),
    sa.Column('special_category_types', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('has_automated_decision_making', sa.Boolean(), nullable=False),
    sa.Column('automated_decision_description', sa.Text(), nullable=True),
    sa.Column('recipient_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_locations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('third_party_transfers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retention_period', sa.Text(), nullable=True),
    sa.Column('security_measures', sa.Text(), nullable=True),
    sa.Column('requires_dpia', sa.Boolean(), nullable=False),
    sa.Column('dpia_completed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='ropastatus'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'auto_generated', name='ropasource'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_profile_id'], ['company_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_ropa_entries_category'), 'ropa_entries', ['category'], unique=False)
    op.create_index(op.f('ix_ropa_entries_legal_basis'), 'ropa_entries', ['legal_basis'], unique=False)
    op.create_index(op.f('ix_ropa_entries_regulation_id'), 'ropa_entries', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_ropa_entries_source_profile_id'), 'ropa_entries', ['source_profile_id'], unique=False)
    op.create_index(op.f('ix_ropa_entries_status'), 'ropa_entries', ['status'], unique=False)
    op.create_index(op.f('ix_ropa_entries_tenant_id'), 'ropa_entries', ['tenant_id'], unique=False)
    # RLS
    op.execute("ALTER TABLE ropa_entries ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ropa_entries FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON ropa_entries
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON ropa_entries")
    op.execute("ALTER TABLE ropa_entries DISABLE ROW LEVEL SECURITY")
    op.drop_index(op.f('ix_ropa_entries_tenant_id'), table_name='ropa_entries')
    op.drop_index(op.f('ix_ropa_entries_status'), table_name='ropa_entries')
    op.drop_index(op.f('ix_ropa_entries_source_profile_id'), table_name='ropa_entries')
    op.drop_index(op.f('ix_ropa_entries_regulation_id'), table_name='ropa_entries')
    op.drop_index(op.f('ix_ropa_entries_legal_basis'), table_name='ropa_entries')
    op.drop_index(op.f('ix_ropa_entries_category'), table_name='ropa_entries')
    op.drop_table('ropa_entries')
    op.execute("DROP TYPE IF EXISTS ropastatus")
    op.execute("DROP TYPE IF EXISTS ropasource")
    op.execute("DROP TYPE IF EXISTS ropalegalbasis")
    op.execute("DROP TYPE IF EXISTS ropadatarole")
