"""add_breach_incidents_table

Revision ID: 753171fcbb47
Revises: 385081b467cb
Create Date: 2026-06-20 15:37:07.275583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '753171fcbb47'
down_revision: Union[str, Sequence[str], None] = '385081b467cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breach_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('breach_type', sa.Enum('confidentiality', 'integrity', 'availability', 'combined', name='breachtype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='breachseverity'), nullable=False),
    sa.Column('regulation', sa.Enum('gdpr', 'nis2', 'both', name='breachregulation'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affected_individual_count', sa.Integer(), nullable=True),
    sa.Column('data_categories_affected', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'under_investigation', 'reported_to_dpa', 'reported_to_individuals', 'closed', name='breachstatus'), nullable=False),
    sa.Column('notification_required', sa.Boolean(), nullable=False),
    sa.Column('dpa_notified', sa.Boolean(), nullable=False),
    sa.Column('dpa_notification_date', sa.Date(), nullable=True),
    sa.Column('individuals_notified', sa.Boolean(), nullable=False),
    sa.Column('individuals_notification_date', sa.Date(), nullable=True),
    sa.Column('containment_measures', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('remediation_steps', sa.Text(), nullable=True),
    sa.Column('ai_notification_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_breach_incidents_severity'), 'breach_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_breach_incidents_status'), 'breach_incidents', ['status'], unique=False)
    op.create_index(op.f('ix_breach_incidents_tenant_id'), 'breach_incidents', ['tenant_id'], unique=False)
    op.create_table('dsar_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.Enum('access', 'rectification', 'erasure', 'portability', 'restriction', 'objection', 'withdraw_consent', name='dsarrequesttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('identity_verification_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'awaiting_info', 'completed', 'rejected', 'withdrawn', name='dsarstatus'), nullable=False),
    sa.Column('assigned_to', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_dsar_requests_request_type'), 'dsar_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_dsar_requests_status'), 'dsar_requests', ['status'], unique=False)
    op.create_index(op.f('ix_dsar_requests_tenant_id'), 'dsar_requests', ['tenant_id'], unique=False)
    op.execute("ALTER TABLE breach_incidents ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE breach_incidents FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON breach_incidents
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)
    op.execute("ALTER TABLE dsar_requests ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE dsar_requests FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON dsar_requests
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsar_requests_tenant_id'), table_name='dsar_requests')
    op.drop_index(op.f('ix_dsar_requests_status'), table_name='dsar_requests')
    op.drop_index(op.f('ix_dsar_requests_request_type'), table_name='dsar_requests')
    op.drop_table('dsar_requests')
    op.drop_index(op.f('ix_breach_incidents_tenant_id'), table_name='breach_incidents')
    op.drop_index(op.f('ix_breach_incidents_status'), table_name='breach_incidents')
    op.drop_index(op.f('ix_breach_incidents_severity'), table_name='breach_incidents')
    op.drop_table('breach_incidents')
    # ### end Alembic commands ###
