"""add_policies_and_policy_versions_tables

Revision ID: a6d7c5a15e41
Revises: 653d73ea41c8
Create Date: 2026-06-10 00:00:08.806411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6d7c5a15e41'
down_revision: Union[str, Sequence[str], None] = '653d73ea41c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('privacy_notice', 'ropa', 'dpa', 'cookie_policy', 'data_retention', 'incident_response', 'ai_governance', 'other', name='policytype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'under_review', 'archived', name='policystatus'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('content_format', sa.Enum('markdown', 'plain_text', name='policycontentformat'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_ai_enhanced', sa.Boolean(), nullable=False),
    sa.Column('regulation_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('related_article', sa.String(length=100), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id')
    )
    op.create_index(op.f('ix_policies_assessment_id'), 'policies', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_policies_regulation_id'), 'policies', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_policies_type'), 'policies', ['type'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('policy_id', sa.String(length=20), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'under_review', 'archived', name='policystatus'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('content_format', sa.Enum('markdown', 'plain_text', name='policycontentformat'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_ai_enhanced', sa.Boolean(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('change_type', sa.Enum('created', 'edited', 'ai_enhanced', 'approved', 'archived', name='policychangetype'), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_tenant_id'), 'policy_versions', ['tenant_id'], unique=False)
    # RLS
    op.execute("ALTER TABLE policies ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON policies
        USING (tenant_id = current_setting('app.current_tenant_id', true))
    """)
    op.execute("ALTER TABLE policy_versions ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON policy_versions
        USING (tenant_id = current_setting('app.current_tenant_id', true))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_versions_tenant_id'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_policies_type'), table_name='policies')
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_regulation_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_assessment_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
