"""use_clerk_ids_as_primary_identifiers

Revision ID: b16e347059d2
Revises: 687a949bb0e5
Create Date: 2026-05-19 19:20:16.579082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16e347059d2'
down_revision: Union[str, Sequence[str], None] = '687a949bb0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop RLS policies that depend on tenant_id columns before altering types
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON company_profile_versions")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON company_profiles")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON tenants")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON users")

    # Alter column types
    op.alter_column('company_profile_versions', 'tenant_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('company_profile_versions', 'changed_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('company_profiles', 'tenant_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tenants', 'tenant_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('tenants_clerk_org_id_key'), 'tenants', type_='unique')
    op.drop_column('tenants', 'clerk_org_id')
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('users_clerk_user_id_key'), 'users', type_='unique')
    op.drop_column('users', 'clerk_user_id')

    # Recreate RLS policies
    op.execute("""
        CREATE POLICY tenant_isolation ON tenants
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)
    op.execute("""
        CREATE POLICY tenant_isolation ON users
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)
    op.execute("""
        CREATE POLICY tenant_isolation ON company_profiles
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)
    op.execute("""
        CREATE POLICY tenant_isolation ON company_profile_versions
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_clerk_user_id_key'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('tenants', sa.Column('clerk_org_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('tenants_clerk_org_id_key'), 'tenants', ['clerk_org_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'tenant_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('company_profiles', 'tenant_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('company_profile_versions', 'changed_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('company_profile_versions', 'tenant_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
