"""create_company_profile_tables

Revision ID: ed4f2bc84da8
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 15:45:19.847278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed4f2bc84da8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.Enum('TECHNOLOGY', 'HEALTHCARE', 'FINANCE', 'LEGAL', 'RETAIL', 'EDUCATION', 'MANUFACTURING', 'OTHER', name='industry'), nullable=True),
    sa.Column('company_size', sa.Enum('ONE_TO_TEN', 'ELEVEN_TO_FIFTY', 'FIFTY_ONE_TO_TWO_HUNDRED', 'TWO_HUNDRED_TO_THOUSAND', 'OVER_THOUSAND', name='companysize'), nullable=True),
    sa.Column('b2b_or_b2c', sa.Enum('B2B', 'B2C', 'BOTH', name='b2borb2c'), nullable=True),
    sa.Column('number_of_data_subjects', sa.Enum('UNDER_1K', 'UNDER_10K', 'UNDER_100K', 'OVER_100K', name='numberofdatasubjects'), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('primary_jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('uses_cloud_services', sa.Boolean(), nullable=True),
    sa.Column('cloud_providers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_cloud_region', sa.String(length=100), nullable=True),
    sa.Column('has_on_premise_servers', sa.Boolean(), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_compliance_officer', sa.Boolean(), nullable=True),
    sa.Column('dpo_name', sa.String(length=255), nullable=True),
    sa.Column('dpo_email', sa.String(length=255), nullable=True),
    sa.Column('legal_contact_email', sa.String(length=255), nullable=True),
    sa.Column('data_categories_processed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_purposes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_subject_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_audit_date', sa.Date(), nullable=True),
    sa.Column('previous_regulatory_action', sa.Boolean(), nullable=True),
    sa.Column('regulatory_authority', sa.String(length=255), nullable=True),
    sa.Column('gdpr_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nis2_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_act_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_company_profiles_tenant_id'), 'company_profiles', ['tenant_id'], unique=False)
    op.create_table('company_profile_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.String(length=20), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('industry', sa.Enum('TECHNOLOGY', 'HEALTHCARE', 'FINANCE', 'LEGAL', 'RETAIL', 'EDUCATION', 'MANUFACTURING', 'OTHER', name='industry'), nullable=True),
    sa.Column('company_size', sa.Enum('ONE_TO_TEN', 'ELEVEN_TO_FIFTY', 'FIFTY_ONE_TO_TWO_HUNDRED', 'TWO_HUNDRED_TO_THOUSAND', 'OVER_THOUSAND', name='companysize'), nullable=True),
    sa.Column('gdpr_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nis2_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_act_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_index(op.f('ix_company_profile_versions_profile_id'), 'company_profile_versions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_company_profile_versions_tenant_id'), 'company_profile_versions', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('gdpr_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tenants', sa.Column('nis2_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tenants', sa.Column('ai_act_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Enable RLS on company_profiles
    op.execute("ALTER TABLE company_profiles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE company_profiles FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON company_profiles
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)

    # Enable RLS on company_profile_versions
    op.execute("ALTER TABLE company_profile_versions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE company_profile_versions FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON company_profile_versions
        USING (tenant_id = current_setting('app.tenant_id', true))
    """)

    # Grant app_user access to new tables
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON company_profiles TO app_user")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON company_profile_versions TO app_user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON company_profile_versions")
    op.execute("ALTER TABLE company_profile_versions DISABLE ROW LEVEL SECURITY")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON company_profiles")
    op.execute("ALTER TABLE company_profiles DISABLE ROW LEVEL SECURITY")

    op.drop_column('tenants', 'ai_act_enabled')
    op.drop_column('tenants', 'nis2_enabled')
    op.drop_column('tenants', 'gdpr_enabled')
    op.drop_index(op.f('ix_company_profile_versions_tenant_id'), table_name='company_profile_versions')
    op.drop_index(op.f('ix_company_profile_versions_profile_id'), table_name='company_profile_versions')
    op.drop_table('company_profile_versions')
    op.drop_index(op.f('ix_company_profiles_tenant_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
